WITH ITEM_CTE AS (
    SELECT 
    IT.ITEM_ID AS ITEM_ID
    FROM ITEM_INFO II
    LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
    WHERE IT.PARENT_ITEM_ID IS NOT NULL
    AND II.RARITY = 'RARE'
)
SELECT I_I.ITEM_ID, I_I.ITEM_NAME, I_I.RARITY
FROM ITEM_CTE IC
INNER JOIN ITEM_INFO I_I ON IC.ITEM_ID = I_I.ITEM_ID
ORDER BY 1 DESC;