SELECT
    I_2.ITEM_ID,
    I_2.ITEM_NAME,
    I_2.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO I_2 ON T.ITEM_ID = I_2.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY 1 DESC;