WITH TF AS (
    SELECT CC.CAR_ID AS CAR_ID, 
           CC.CAR_TYPE AS CAR_TYPE,
            (CC.DAILY_FEE*30*(100-CP.DISCOUNT_RATE)/100) AS TOTAL_FEE
    FROM CAR_RENTAL_COMPANY_CAR CC
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
    ON CC.CAR_TYPE = CP.CAR_TYPE
    WHERE (CP.DURATION_TYPE = '30일 이상')
    AND ((CC.CAR_TYPE = '세단') OR (CC.CAR_TYPE = 'SUV'))
),
RT AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
    AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
)
SELECT DISTINCT TF.CAR_ID, TF.CAR_TYPE, TF.TOTAL_FEE
FROM TF
WHERE TF.CAR_ID NOT IN (SELECT CAR_ID FROM RT)
AND (TF.TOTAL_FEE >= 500000 AND TF.TOTAL_FEE < 2000000)
ORDER BY TF.TOTAL_FEE DESC, TF.CAR_TYPE, TF.CAR_ID DESC;