WITH SCORE_CTE AS (
        SELECT 
            EMP_NO, 
            SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
        ORDER BY SUM_SCORE DESC
        LIMIT 1
        )
    
SELECT SC.SUM_SCORE AS SCORE, SC.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
INNER JOIN SCORE_CTE SC
ON HE.EMP_NO = SC.EMP_NO;