WITH CTE_PRICE AS (
    SELECT 
        CATEGORY, 
        PRICE, 
        PRODUCT_NAME, 
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')   
)
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM CTE_PRICE
WHERE RANK = 1
ORDER BY 2 DESC