WITH RECURSIVE CTE_HOUR AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 AS HOUR
    FROM CTE_HOUR
    WHERE HOUR < 23
),
CTE_ANIMAL AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
    ORDER BY 1
)
SELECT CH.HOUR AS HOUR, COALESCE(CA.COUNT, 0) AS COUNT
FROM CTE_HOUR CH
LEFT JOIN CTE_ANIMAL CA ON CH.HOUR = CA.HOUR
ORDER BY 1