SELECT 
    COUNT(FISH_LENGTH) AS FISH_COUNT, 
    MAX(FISH_LENGTH) AS MAX_LENGTH, 
    FISH_TYPE
FROM (
    SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS FISH_LENGTH
    FROM FISH_INFO    
) NEW_FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(FISH_LENGTH) >= 33
ORDER BY 3