WITH CTE_HOUR AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
),
CTE_ANIMAL AS (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')
)
SELECT CH.HOUR, NVL(CA.COUNT, 0) AS COUNT
FROM CTE_HOUR CH
LEFT JOIN CTE_ANIMAL CA ON CH.HOUR = CA.HOUR
ORDER BY CH.HOUR;
