WITH CTE_HOUR AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
),
CTE_ANIMAL AS (
    SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
    ORDER BY 1
)
SELECT CH.HOUR AS HOUR, COALESCE(MAX(CA.COUNT), 0) AS COUNT
FROM CTE_HOUR CH
LEFT JOIN CTE_ANIMAL CA ON CH.HOUR = CA.HOUR
GROUP BY CH.HOUR
ORDER BY 1
