SELECT
    EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH,
    UI.GENDER AS GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE OS
LEFT JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM OS.SALES_DATE),
    EXTRACT(MONTH FROM OS.SALES_DATE),
    UI.GENDER
ORDER BY 1, 2, 3;