WITH FISH_BS AS (
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO
    WHERE FISH_NAME IN ('BASS', 'SNAPPER')
)
SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_BS FB ON FI.FISH_TYPE = FB.FISH_TYPE
