SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    TO_CHAR(UGR.CREATED_DATE, 'yyyy-mm-dd')
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGB.CREATED_DATE >= DATE '2022-10-01'
AND UGB.CREATED_DATE < DATE '2022-11-01'
ORDER BY 6, 1