WITH Front_CTE AS (
    SELECT NAME, CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT 
    CASE
        WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) != 0
             AND EXISTS (SELECT 1 FROM Front_CTE FC WHERE D.SKILL_CODE & FC.CODE = FC.CODE) THEN 'A'
        WHEN (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) != 0 THEN 'B'
        WHEN EXISTS (SELECT 1 FROM Front_CTE FC WHERE D.SKILL_CODE & FC.CODE = FC.CODE) THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
WHERE (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) != 0
    OR EXISTS (SELECT 1 FROM Front_CTE FC WHERE D.SKILL_CODE & FC.CODE = FC.CODE)
ORDER BY 1, 2;