WITH Front_CTE AS (
    SELECT NAME, CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
TARGET AS (
    SELECT 
    CASE
        WHEN (D.SKILL_CODE & 256 = 256) AND EXISTS (SELECT 1 FROM Front_CTE FC WHERE D.SKILL_CODE & FC.CODE = FC.CODE) THEN 'A'
        WHEN (D.SKILL_CODE & 1024 = 1024) THEN 'B'
        WHEN EXISTS (SELECT 1 FROM Front_CTE FC WHERE D.SKILL_CODE & FC.CODE = FC.CODE) THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
    FROM DEVELOPERS D
    ORDER BY 1, 2
)
SELECT *
FROM TARGET
WHERE GRADE IS NOT NULL