WITH ID_CTE AS (
    SELECT HISTORY_ID, CAR_ID, START_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= DATE '2022-08-01'
    AND START_DATE < DATE '2022-11-01'
),
COUNT_CTE AS (
    SELECT DISTINCT CAR_ID
    FROM ID_CTE
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
),
DATE_CTE AS (
    SELECT HISTORY_ID,
           CAR_ID,
           EXTRACT(MONTH FROM START_DATE) AS MON
    FROM ID_CTE 
)
SELECT MON AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM DATE_CTE
WHERE CAR_ID IN (SELECT CAR_ID FROM COUNT_CTE)
GROUP BY MON, CAR_ID
ORDER BY MON ASC, CAR_ID DESC;