WITH CANT_AVAI AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE DATE '2022-10-16' <= END_DATE
    AND DATE '2022-10-16' >= START_DATE
    GROUP BY CAR_ID
),
CAR_ID_LIST AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT CAR_ID,
    CASE
        WHEN CAR_ID NOT IN (SELECT CAR_ID FROM CANT_AVAI) THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM CAR_ID_LIST
ORDER BY CAR_ID DESC