WITH RANK_LENGTH_CTE AS (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN
    FROM FISH_INFO FI
)
SELECT
    RLC.ID,
    FNI.FISH_NAME,
    RLC.LENGTH  
FROM RANK_LENGTH_CTE RLC
LEFT JOIN FISH_NAME_INFO FNI ON RLC.FISH_TYPE = FNI.FISH_TYPE
WHERE RLC.RN = 1
ORDER BY 1