SELECT 
    HG.EMP_NO, 
    HE.EMP_NAME, 
    CASE 
        WHEN SUM(SCORE)/2 >= 96 THEN 'S'
        WHEN SUM(SCORE)/2 >= 90 THEN 'A'
        WHEN SUM(SCORE)/2 >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SUM(SCORE)/2 >= 96 THEN 0.2 * HE.SAL
        WHEN SUM(SCORE)/2 >= 90 THEN 0.15 * HE.SAL
        WHEN SUM(SCORE)/2 >= 80 THEN 0.1 * HE.SAL
        ELSE 0
    END AS BONUS
FROM HR_GRADE HG
LEFT JOIN HR_EMPLOYEES HE ON HG.EMP_NO = HE.EMP_NO
GROUP BY HG.EMP_NO, HE.EMP_NAME
ORDER BY 1