WITH RECURSIVE GENERATION_CTE AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        E.ID,
        E.PARENT_ID,
        (G.GENERATION + 1) AS GENERATION 
    FROM ECOLI_DATA E
    INNER JOIN GENERATION_CTE G ON E.PARENT_ID = G.ID
)
SELECT ID
FROM GENERATION_CTE
WHERE GENERATION = 3
ORDER BY ID ASC;