SELECT NAME, DATETIME
FROM (
    SELECT AI.NAME, AI.DATETIME, RANK() OVER (ORDER BY AI.DATETIME ASC) AS RN
    FROM ANIMAL_INS AI
    LEFT OUTER JOIN ANIMAL_OUTS AO
    ON AI.ANIMAL_ID = AO.ANIMAL_ID
    WHERE AO.DATETIME IS NULL
    ) ANIMAL
WHERE RN <= 3;