SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
INNER JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE REGEXP_LIKE(AI.SEX_UPON_INTAKE, 'Intact', 'i')
AND (REGEXP_LIKE(AO.SEX_UPON_OUTCOME, 'Spayed', 'i') OR REGEXP_LIKE(AO.SEX_UPON_OUTCOME, 'Neutered'))
ORDER BY AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME;